/** @type {import('tailwindcss').Config} */

const defaultTheme = require("tailwindcss/defaultTheme");

export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["InstrumentSans", ...defaultTheme.fontFamily.sans],
        serif: ["InstrumentSerif", ...defaultTheme.fontFamily.serif],
        mono: ["VictorMono", ...defaultTheme.fontFamily.mono],
      },
      colors: {
        twine: {
          50: "#fcfbf5",
          100: "#f7f4e9",
          200: "#f0e8ce",
          300: "#e6d9b3",
          400: "#d1b780",
          500: "#bd9653",
          600: "#ab8244",
          700: "#8c622e",
          800: "#70471d",
          900: "#543011",
          950: "#361a07",
        },
        fitzgerald: {
          50: "#f7f7f5",
          100: "#f0efeb",
          200: "#d6d4ce",
          300: "#bfbbb4",
          400: "#8f897f",
          500: "#5e574f",
          600: "#544a40",
          700: "#47392d",
          800: "#38281c",
          900: "#2b1b10",
          950: "#1c0e07",
        },
        impossible: {
          50: "#f2f7f5",
          100: "#e6f0ec",
          200: "#c5dbd1",
          300: "#a5c4b4",
          400: "#70997e",
          500: "#426d4c",
          600: "#376340",
          700: "#26522e",
          800: "#194220",
          900: "#0d3013",
          950: "#061f09",
        },
      },
      typography: ({ theme }) => ({
        impossible: {
          css: {
            "--tw-prose-body": theme("colors.fitzgerald[800]"),
            "--tw-prose-headings": theme("colors.impossible[500]"),
            "--tw-prose-lead": theme("colors.fitzgerald[700]"),
            "--tw-prose-links": theme("colors.impossible[500]"),
            "--tw-prose-bold": theme("colors.fitzgerald[900]"),
            "--tw-prose-counters": theme("colors.fitzgerald[600]"),
            "--tw-prose-bullets": theme("colors.fitzgerald[400]"),
            "--tw-prose-hr": theme("colors.fitzgerald[300]"),
            "--tw-prose-quotes": theme("colors.fitzgerald[900]"),
            "--tw-prose-quote-borders": theme("colors.fitzgerald[300]"),
            "--tw-prose-captions": theme("colors.fitzgerald[700]"),
            "--tw-prose-code": theme("colors.fitzgerald[900]"),
            "--tw-prose-pre-code": theme("colors.fitzgerald[100]"),
            "--tw-prose-pre-bg": theme("colors.fitzgerald[900]"),
            "--tw-prose-th-borders": theme("colors.fitzgerald[300]"),
            "--tw-prose-td-borders": theme("colors.fitzgerald[200]"),
            "--tw-prose-invert-body": theme("colors.fitzgerald[200]"),
            "--tw-prose-invert-headings": theme("colors.impossible[500]"),
            "--tw-prose-invert-lead": theme("colors.fitzgerald[300]"),
            "--tw-prose-invert-links": theme("colors.impossible[500]"),
            "--tw-prose-invert-bold": theme("colors.impossible[500]"),
            "--tw-prose-invert-counters": theme("colors.fitzgerald[400]"),
            "--tw-prose-invert-bullets": theme("colors.fitzgerald[600]"),
            "--tw-prose-invert-hr": theme("colors.fitzgerald[700]"),
            "--tw-prose-invert-quotes": theme("colors.fitzgerald[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.fitzgerald[700]"),
            "--tw-prose-invert-captions": theme("colors.fitzgerald[400]"),
            "--tw-prose-invert-code": theme("colors.impossible[500]"),
            "--tw-prose-invert-pre-code": theme("colors.fitzgerald[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.fitzgerald[600]"),
            "--tw-prose-invert-td-borders": theme("colors.fitzgerald[700]"),
          },
        },
      }),
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/aspect-ratio"),
  ],
};
